default_language_version:
    python: python3

exclude: ^[.]

repos:
    - repo: https://github.com/netromdk/vermin
      rev: v1.7.0
      hooks:
          - id: vermin
            args:
                - -t=3.8-
                - --violations
                - --verbose
                - --eval-annotations
                - --backport
                - argparse
                - --backport
                - typing
